### ISSUE TITLE
Required parameter `$packageName` follows optional parameter `$packageTranslationsDir`

### ISSUE THREAD

**Issue by canvural** [optimistdigital/nova-translations-loader#1]
[Here](https://github.com/optimistdigital/nova-translations-loader/blob/master/src/NovaTranslationsLoader.php#L16) and [here](https://github.com/optimistdigital/nova-translations-loader/blob/master/src/NovaTranslationsLoader.php#L32) required parameter `$packageName` is after a optional parameter `$packageTranslationsDir`

Either the order should be changed, or `$packageName` should also have a default value.

(Found this when tried to run the project with PHP8)

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this! Fixed it and released the fix in version 1.0.5.
