### ISSUE TITLE
Unnecessary drop of support for Laravel < 9

### ISSUE THREAD

**Issue by pavoltanuska** [optimistdigital/nova-translations-loader#14]
As far as I can see, the only code [difference between 4.0.1 and 3.1.4](https://github.com/outl1ne/nova-translations-loader/compare/3.1.4...4.0.1) is changing the function call from `resource_path('lang/...')` to `lang_path('...')`

Is it really necessary to drop the support for (at least) Laravel 8?

My situation:
I'm upgrading Nova 3 -> 4. Upgrade of Laravel 8 -> 9 is planned for the near future, but does not fit my current schedule.
Your [multiselect package](https://github.com/outl1ne/nova-multiselect-field) depends on this one and it has hard Laravel >= 9 dependency.
Thus I'm not able to proceed with the upgrade (without any hacks at least).

**Comment by Tarpsvo** [comment]
Heya! The new version 5 of the translations loader should support PHP 8.0 and Laravel 8.0 again. I also updated the multiselect field to use version 5. Good luck!
