### ISSUE TITLE
Call to undefined method getFallbackLocale

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [optimistdigital/nova-translations-loader#2]
Hi, 
I've just run composer update and found an error like below:
Do you know what could happened ?

`"class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError"    
"message": "Call to undefined method Illuminate\\Foundation\\Application::getFallbackLocale()",   
"file": "vendor/optimistdigital/nova-translations-loader/src/LoadsNovaTranslations.php:70",
"vendor/optimistdigital/nova-translations-loader/src/LoadsNovaTranslations.php:45"`

I have Laravel v 6.20

**Comment by Tarpsvo** [comment]
Can you upgrade to Laravel 7? 🙄

**Comment by Tarpsvo** [comment]
`app()->getFallbackLocale()` was apparently added in Laravel 7. I could work around this, but I think I'd rather just support the latest two versions of Laravel in the latest versions of the packages. In this case, that would be Laravel 7 and 8.

**Comment by PrzemekTkaczyk** [comment]
OK, thank you, 
Yes, I will do this... it is quite a big project and I delayed it :)

**Comment by PrzemekTkaczyk** [comment]
After the update, it works fine, thanks! 👍

**Comment by nbyloff** [comment]
I am stuck on Laravel 6; LTS is required for this project so I can't bump this version until the LTS gets bumped. Rolling back the to the following works for me. I'll fork this project until contracts let me update to the latest version. 

````
$fbLocale = config('app.fallback_locale');
````

Side note, anyone from google seeing this Nova support 2.X stays patched with L6 updates.

**Comment by condor-bird** [comment]
Hi,
I also faced similar issue on Laravel v7. Is it possible to expect a fix in the near future?

**Comment by Tarpsvo** [comment]
Laravel 7 should support getFallbackLocale, starting from 7.21. Can you try upgrading?

**Comment by condor-bird** [comment]
My Laravel version is v7.14.1, it is likely that it did not yet support this method at that time. Yes, I will try to update, although it will probably not be done quickly. Thank you.
