### ISSUE TITLE
ErrorException array_merge(): Expected parameter 2 to be an array, null given

### ISSUE THREAD

**Issue by Jaspur** [optimistdigital/nova-translations-loader#3]
Failing here
/optimistdigital/nova-translations-loader/src/LoadsNovaTranslations.php:61:

 ```
  private function loadNovaTranslations($locale, $from, $packageTranslationsDir, $packageName)
    {
        $translationsFile = $this->getTranslationsFile($locale, $from, $packageTranslationsDir, $packageName);
        if ($translationsFile) {
            Nova::translations($translationsFile);
            return true;
        }
        return false;
    }

```

**Comment by Tarpsvo** [comment]
That's really weird. Doesn't the `if` check avoid this? How can it crash?

**Comment by Tarpsvo** [comment]
Is your JSON correct? It could crash due to json_decode failing.

Nova::translations code:

```
public static function translations($translations)
    {
        if (is_string($translations)) {
            if (! is_readable($translations)) {
                return new static;
            }

            $translations = json_decode(file_get_contents($translations), true); // <-- if this fails, it would return null
        }

        static::$translations = array_merge(static::$translations, $translations);

        return new static;
    }
```

**Comment by Jaspur** [comment]
I downgraded to 2.0.1 and there it works, probably something to do with the rework on it you've done

**Comment by Tarpsvo** [comment]
What package are you using?

**Comment by Jaspur** [comment]
Maybe strange thinking, but is it maybe related that the application is running on a Vapor instance..?

**Comment by Tarpsvo** [comment]
I wouldn't think that matters, no.

Is this the same error? In Nova.php? https://d.pr/i/ofZHeX

**Comment by Jaspur** [comment]
Yes

**Comment by Tarpsvo** [comment]
That would seem to show that the JSON you are loading is not valid. It doesn't pass `json_decode()`. Can you validate the translations JSON?

**Comment by Tarpsvo** [comment]
Added a failsafe for that in the latest version, it should check if the JSON is valid now.
