### ISSUE TITLE
Nova::translations method not found, please ensure you are using the correct version of Nova.

### ISSUE THREAD

**Issue by AnandPilania** [optimistdigital/nova-translations-loader#5]
Using:

> laravel/nova: ^3.22,
> optimistdigital/nova-multiselect-field: ^2.0

Error:

> OptimistDigital\MultiselectField\FieldServiceProvider::translations
> ...\vendor\optimistdigital\nova-translations-loader\src\LoadsNovaTranslations.php:40

Steps:

> JUST INSTALLED FRESH LARAVEL/NOVA WITH MULTISELECT-FIELD & `SERVE` THE PROJECT

Regards

**Comment by Tarpsvo** [comment]
Added a theoretical improvement on that regard. Please try it with the latest version. :) Thanks!
