### ISSUE TITLE
Translations work fine for the translated package, but stop working for the rest of Nova

### ISSUE THREAD

**Issue by ramonfeleus** [optimistdigital/nova-translations-loader#6]
In gldrenthe89/nova-string-generator-field I've used load translations as follows:
`$this->loadTranslations(__DIR__ . '/../resources/lang', 'nova-string-generator-field', true);`
The translations are located in resources/lang/ of that package.
In the Vue files translations are working fine.
However the rest of my Nova backend that had working translations (in dutch, 'nl', fallback 'en') for menu items, buttons, fields stopped being translated.
I've traced it back to the translations function of LoadsNovaTranslations.php of this package.
When I disable the line `$this->loadLaravelTranslations($pckgTransDir, $pckgName);` all translations are working, both the nova-string-generator-field vue component and the rest of my nova backend.
It also works when I move it to the bottom of the `Nova::serving(function (ServingNova $event) use ($pckgTransDir, $pckgName) {` line. But when it's before the `if ($this->loadNovaTranslations` lines it stops working.
Could you please check if moving `$this->loadLaravelTranslations($pckgTransDir, $pckgName);` to the bottom is the correct fix for this issue?

**Comment by ramonfeleus** [comment]
I've created a pull request with a fix that works in 2 of my projects: https://github.com/optimistdigital/nova-translations-loader/pull/7

**Comment by Tarpsvo** [comment]
I merged it at first, but then I noticed - the whole function returns while loading Nova translations, so it never reached the `loadLaravelTranslations` part (which means, all other packages will break as Laravel won't have access to the required translations). There's something else going on here. If you can, can you check if the line:

```
app('translator')->addLines($translations, $locale);
```

causes the translations to go missing. If so, can you log out `$translations` and `$locale` for me? Thanks!

**Comment by Tarpsvo** [comment]
Holy crap! There was a fix for that exact issue in version 3.1.1 - BUT! I forgot to release 3.1.1. Now that I released 3.1.2 instead, please try it out and tell me if it works now. It was back in december that I fixed it, so I forgot. I am 99% sure that your issue was fixed in 3.1.2. :D

**Comment by ramonfeleus** [comment]
Haha, excellent!  Yes, it's working over here with the update, closing the issue :-)
