### ISSUE TITLE
Wrong requirements - getFallbackLocale() undefined

### ISSUE THREAD

**Issue by kobeyy** [optimistdigital/nova-translations-loader#8]
When installing the package on laravel 7.19 i got the following error:

Call to undefined method Illuminate\Foundation\Application::getFallbackLocale()
`OptimistDigital\MultiselectField\FieldServiceProvider::loadLaravelTranslations`

## Possible fixes:
**Make getFallbackLocale() call optional**
Did not have time to implement concrete fix.

**Fix requirements:**
specify laravel version based on the release notes:
https://github.com/laravel/framework/releases/tag/v7.21.0

https://github.com/optimistdigital/nova-translations-loader/blob/e19fd466c7afa68aab6300f8b6f834a35ed1c7bc/composer.json#L13
=> `^7.21.x || ^8.x`

**Comment by Tarpsvo** [comment]
Bumped the minimum version to 7.21. Thank you! :)
